# Generated by Django 4.1.3 on 2022-11-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='status',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
