# Generated by Django 4.1.3 on 2022-11-25 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_seat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='garage_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.garage', verbose_name='Garage'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musty', models.CharField(max_length=100)),
                ('garage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.garage', verbose_name='Garage')),
            ],
        ),
    ]
