# Generated by Django 4.1.3 on 2022-11-27 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_alter_trip_garage_id_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manager',
            name='garage_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='managers.garage', verbose_name='Garage'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='schedule_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='managers.schedule', verbose_name='Schedule'),
        ),
        migrations.AddField(
            model_name='trip',
            name='num_seat',
            field=models.IntegerField(default=0),
        ),
    ]
