# Generated by Django 4.1.3 on 2022-11-29 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0006_rename_garage_id_manager_garage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garage',
            old_name='description',
            new_name='description',
        ),
    ]
