# Generated by Django 4.1.3 on 2022-12-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0009_schedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='departure_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
